#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"

case "`uname`" in
    Darwin* )
        binary=bazelisk-darwin-amd64
        ;;
    Linux* )
        binary=bazelisk-linux-amd64
        ;;
esac

if [ -z ${binary+x} ];
then
    echo "Unable to resolve system type"
    exit 1
else
    exec "${DIR}/bin/${binary}" "$@"
fi
