//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 08:41:14 PM EET 
//

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import fi.eonwe.wikilinks.jaxb.CommentType;
import fi.eonwe.wikilinks.jaxb.ContributorType;
import fi.eonwe.wikilinks.jaxb.DiscussionThreadingInfo;
import fi.eonwe.wikilinks.jaxb.LogItemType;
import fi.eonwe.wikilinks.jaxb.LogParamsType;
import fi.eonwe.wikilinks.jaxb.LogTextType;
import fi.eonwe.wikilinks.jaxb.MediaWikiType;
import fi.eonwe.wikilinks.jaxb.NamespaceType;
import fi.eonwe.wikilinks.jaxb.NamespacesType;
import fi.eonwe.wikilinks.jaxb.ObjectFactory;
import fi.eonwe.wikilinks.jaxb.PageType;
import fi.eonwe.wikilinks.jaxb.RedirectType;
import fi.eonwe.wikilinks.jaxb.RevisionType;
import fi.eonwe.wikilinks.jaxb.SiteInfoType;
import fi.eonwe.wikilinks.jaxb.TextType;
import fi.eonwe.wikilinks.jaxb.UploadType;

public class JAXBDebug {


    public static JAXBContext createContext(ClassLoader classLoader)
        throws JAXBException
    {
        return JAXBContext.newInstance(MediaWikiType.class, SiteInfoType.class, NamespacesType.class, NamespaceType.class, RedirectType.class, PageType.class, RevisionType.class, LogItemType.class, CommentType.class, TextType.class, LogTextType.class, LogParamsType.class, ContributorType.class, UploadType.class, DiscussionThreadingInfo.class, ObjectFactory.class);
    }

}
