//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 08:24:04 PM EET 
//


package fi.eonwe.wikilinks.jaxb;

import java.math.BigInteger;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for NamespaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NamespaceType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="case" type="{http://www.mediawiki.org/xml/export-0.8/}CaseType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamespaceType", propOrder = {
    "value"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
public class NamespaceType {

    @XmlValue
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    protected String value;
    @XmlAttribute(name = "key")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    protected BigInteger key;
    @XmlAttribute(name = "case")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    protected CaseType _case;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    public BigInteger getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    public void setKey(BigInteger value) {
        this.key = value;
    }

    /**
     * Gets the value of the case property.
     * 
     * @return
     *     possible object is
     *     {@link CaseType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    public CaseType getCase() {
        return _case;
    }

    /**
     * Sets the value of the case property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:24:04+02:00", comments = "JAXB RI v2.2.11")
    public void setCase(CaseType value) {
        this._case = value;
    }

}
