//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 08:18:45 PM EET 
//


package fi.eonwe.wikilinks;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SiteInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SiteInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sitename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="base" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element name="generator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="case" type="{http://www.mediawiki.org/xml/export-0.8/}CaseType" minOccurs="0"/&gt;
 *         &lt;element name="namespaces" type="{http://www.mediawiki.org/xml/export-0.8/}NamespacesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SiteInfoType", propOrder = {
    "sitename",
    "base",
    "generator",
    "_case",
    "namespaces"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
public class SiteInfoType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    protected String sitename;
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    protected String base;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    protected String generator;
    @XmlElement(name = "case")
    @XmlSchemaType(name = "NMTOKEN")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    protected CaseType _case;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    protected NamespacesType namespaces;

    /**
     * Gets the value of the sitename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public String getSitename() {
        return sitename;
    }

    /**
     * Sets the value of the sitename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public void setSitename(String value) {
        this.sitename = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the generator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public String getGenerator() {
        return generator;
    }

    /**
     * Sets the value of the generator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public void setGenerator(String value) {
        this.generator = value;
    }

    /**
     * Gets the value of the case property.
     * 
     * @return
     *     possible object is
     *     {@link CaseType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public CaseType getCase() {
        return _case;
    }

    /**
     * Sets the value of the case property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public void setCase(CaseType value) {
        this._case = value;
    }

    /**
     * Gets the value of the namespaces property.
     * 
     * @return
     *     possible object is
     *     {@link NamespacesType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public NamespacesType getNamespaces() {
        return namespaces;
    }

    /**
     * Sets the value of the namespaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespacesType }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2015-02-16T08:18:45+02:00", comments = "JAXB RI v2.2.11")
    public void setNamespaces(NamespacesType value) {
        this.namespaces = value;
    }

}
